### PR TITLE
Add Saudi Arabia Schedule

### PR DESCRIPTION
**Pull request by hazeim254**
Please add this file to Asia list

### CODE REVIEW

**Comment by introwit** [comment]
@hazeim254 thank you for the PR Hazem :)

**Comment by nmfzone** [comment]
@hazeim254 I think 12:45 am should be 9th March. Cmiiw

**Comment by atmonshi** [comment]
@hazeim254  also I hope you update the main README.md

**Comment by introwit** [comment]
@hazeim254 done brother :) @nmfzone fixed, thanks!

**Comment by hazeim254** [comment]
Thank you for accepting the PR and for fixing my glitches 😄

**Pull request merged**
