### PR TITLE
Added missing timezones a few fixed 'am' and 'pm'

### PR DESCRIPTION
**Pull request by tonydew**

### CODE REVIEW

**Comment by introwit** [comment]
@tonydew you have changed the timezones! Can you confirm @tfevens please ?

**Comment by tonydew** [comment]
Changed the timezones? No, just added Pacific, Mountain and Central. Also ordered the groups from closest to GMT to farthest, just like usa.md ordering.

**Comment by introwit** [comment]
@tonydew oops! my bad, thanks for the fixes :)

**Comment by tonydew** [comment]
You are welcome. Thanks for the merge!

**Pull request merged**
